---
- name: Make sure nginx user exists
  user:
    name: "{{nginx_user}}"
    shell: /bin/false
    create_home: False

- name: Install nginx
  package:
    name: nginx
    state: present
  tags:
    - nginx

- name: Create nginx sites directory
  file:
    path: "{{ nginx_sites_path }}"
    state: directory
    owner: root
  tags:
    - nginx

- name: Copy basic nginx configuration
  template:
    src: nginx.conf
    dest: "{{ nginx_path }}/nginx.conf"
  tags:
    - nginx
  notify:
    - Reload nginx
    - Nginx config verified

- name: Create dhparams
  command: "openssl dhparam -dsaparam -out {{ nginx_dhparams_path }} {{ nginx_dhparams_size }}"
  args:
    creates: "{{ nginx_dhparams_path }}"
  tags:
    - nginx
  notify:
    - Restart nginx

- name: Install Certbot
  include_tasks: certbot.yml
  when: install_certbot|bool
  tags:
    - nginx
    - certbot
    
- name: Start and enable nginx
  service:
    name: nginx
    state: started
    enabled: yes
  tags:
    - nginx

- name: Configure firewalld
  include_tasks: firewalld.yml
  when: "'firewalld' in ansible_facts.packages"
...    
